/* Exports upload material for the Google Business Profile.

   Reads IMAGE-MANIFEST.md, takes the strongest images that are actually
   placed on the site, and writes them to gbp/ as JPEGs at 1200px on the long
   edge, with a captions.txt mapping each file to a suggested caption drawn
   from its manifest subject row.

   Skips every row marked "do not place" or "HELD" — the withdrawn and held
   images must not leave the repo.

   These are NOT site assets. gbp/ is gitignored.

   Usage: node tools/gbp-export.js */
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const sharp = require(path.join(ROOT, 'triage', 'node_modules', 'sharp'));

const LIMIT = 20;
const OUT = path.join(ROOT, 'gbp');

/* Ranking. Google's own guidance favours the exterior, the interior, the team
   and the goods, roughly in that order, so the export leads with those. */
const PRIORITY = [
  'storefront-exterior-01.webp',
  'staff-portrait-storefront-01.webp',
  'service-counter-portrait-01.webp',
  'interior-aisle-01.webp',
  'interior-aisle-numbered-01.webp',
  'dept-paint-color-wall-01.webp',
  'dept-paint-color-wall-03.webp',
  'dept-paint-color-center-01.webp',
  'service-key-cutting-01.webp',
  'service-key-cutting-action-01.webp',
  'service-key-blanks-01.webp',
  'service-key-wall-signage-01.webp',
  'brand-benjamin-moore-sign-01.webp',
  'dept-paint-regal-cans-01.webp',
  'dept-paint-advance-cans-01.webp',
  'dept-fasteners-bins-01.webp',
  'dept-tools-accessories-01.webp',
  'dept-plumbing-traps-01.webp',
  'dept-cleaning-aisle-02.webp',
  'dept-roofing-cement-01.webp',
  'dept-paint-aisle-01.webp',
  'dept-paint-spray-01.webp',
  'dept-fasteners-wall-01.webp',
  'dept-cleaning-brooms-01.webp'
];

/* ---- read the manifest ------------------------------------------------ */
const md = fs.readFileSync(path.join(ROOT, 'IMAGE-MANIFEST.md'), 'utf8');
const rowRe = /^\| `([a-z0-9-]+\.webp)` \| (DSC\d+\.jpg) \| (.*?) \| (.*?) \| (\d+)×(\d+) \| (.*?) \| (.*?) \|$/gm;

const rows = {};
let m;
while ((m = rowRe.exec(md)) !== null) {
  // groups: 1 file, 2 src, 3 subject, 4 depts, 5 w, 6 h, 7 suggested use, 8 alt
  rows[m[1]] = { src: m[2], subject: m[3].trim(), use: m[7].trim(), alt: m[8].trim() };
}

const BLOCKED = /do not place|HELD/i;
const eligible = Object.entries(rows).filter(([, r]) => !BLOCKED.test(r.use));
const blocked = Object.entries(rows).filter(([, r]) => BLOCKED.test(r.use));

/* The guard must never be silently inert: if the manifest says images are
   withdrawn and this finds none, the parse is wrong, not the manifest. */
if (blocked.length === 0) {
  console.error('');
  console.error('ABORT: no withdrawn or held rows found in the manifest.');
  console.error('That is almost certainly a parse failure rather than a clean');
  console.error('manifest - refusing to export in case a withdrawn image slips through.');
  console.error('');
  process.exit(1);
}

console.log(`manifest rows: ${Object.keys(rows).length}`);
console.log(`blocked (withdrawn or held, never exported): ${blocked.length}`);
blocked.forEach(([f]) => console.log('   skip  ' + f));

/* order by the priority list, then whatever else is eligible */
const blockedNames = new Set(blocked.map(([f]) => f));
const ordered = [
  ...PRIORITY.filter(f => eligible.some(([e]) => e === f)),
  ...eligible.map(([f]) => f).filter(f => !PRIORITY.includes(f))
].slice(0, LIMIT);

const leaked = ordered.filter(f => blockedNames.has(f));
if (leaked.length) {
  console.error('ABORT: withdrawn/held image in the export set: ' + leaked.join(', '));
  process.exit(1);
}

/* ---- caption from the subject row ------------------------------------ */
function caption(file) {
  let s = rows[file].subject
    .replace(/\*\*/g, '')
    .replace(/\s*—\s*.*$/, '')     // drop the trailing clause after an em dash
    .replace(/\s*\(.*?\)\s*/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  s = s.charAt(0).toUpperCase() + s.slice(1);
  if (s.length > 140) s = s.slice(0, 137).replace(/\s\S*$/, '') + '…';
  return s.replace(/[.,;]$/, '') + '.';
}

(async () => {
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });

  const lines = [
    'Google Business Profile photo captions',
    'Generated by tools/gbp-export.js from IMAGE-MANIFEST.md',
    '',
    'Upload these to the Business Profile. Captions are suggestions drawn from',
    'the manifest subject rows: they describe only what is visible in the frame.',
    '',
    'Withdrawn and held images are excluded by the tool and must stay excluded.',
    ''
  ];

  let total = 0;
  for (let i = 0; i < ordered.length; i++) {
    const file = ordered[i];
    const src = path.join(ROOT, 'images', file);
    if (!fs.existsSync(src)) { console.error('  missing on disk: ' + file); continue; }
    const outName = String(i + 1).padStart(2, '0') + '-' + file.replace(/\.webp$/, '.jpg');
    const info = await sharp(src)
      .resize({ width: 1200, height: 1200, fit: 'inside', withoutEnlargement: true })
      .jpeg({ quality: 88, chromaSubsampling: '4:4:4' })
      .toFile(path.join(OUT, outName));
    const bytes = fs.statSync(path.join(OUT, outName)).size;
    total += bytes;
    lines.push(`${outName}`);
    lines.push(`    ${caption(file)}`);
    lines.push('');
    console.log(`  ${outName.padEnd(42)} ${info.width}x${info.height}  ${(bytes / 1024).toFixed(0)} KB`);
  }

  fs.writeFileSync(path.join(OUT, 'captions.txt'), lines.join('\n'));
  console.log(`\nwrote ${ordered.length} JPEGs + captions.txt to gbp/  (${(total / 1048576).toFixed(1)} MB)`);
  console.log('gbp/ is gitignored: this is upload material, not site assets.');
})();
